version: "3.9"

services:
  app:
    container_name: codetain-api
    ports:
    - "8000:8000"
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    restart: on-failure
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres-db
    ports: 
    - "8774:5432"
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    restart: on-failure
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: codetain-web
    ports:
    - "4200:4200"
    build:
      context: ../webpanel
      dockerfile: deployment/Dockerfile
    restart: on-failure

  maildev:
    container_name: maildev-server
    image: maildev/maildev
    ports:
    - "1080:1080"

volumes:
  postgres_data: